version: '3'

services:
  control-system:
    build:
      context: ./control-system
      dockerfile: Dockerfile
#    ports:
#       -  "8092:8092"
    depends_on:
      - postgres
      - rabbitmq
      - web_app
      - backend
    env_file:
      - .env
    # ports:
    #   - "8000:8000"

    

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    # volumes:
    #   - ./backend:/backend
    depends_on:
      - postgres
      - rabbitmq



  web_app:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    ports:
      - "8050:8050" # Пример портов для веб-приложения. Измените, если нужно.
    # volumes:
    #   - ./web_app:/web_app # Монтируем каталог с веб-приложением в контейнер
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - .env



  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      # - .env
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb



  rabbitmq:
    # image: rabbitmq:latest
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
